### ISSUE TITLE
Asking for the dataset.

### ISSUE THREAD

**Issue by blldd** [Logan-Lin/CTLE#1]
Hi, very pleased to study your work, could you please add your dataset to this repo, thank you.

**Comment by mzl9039** [comment]
@Logan-Lin  Hi, also interested in your work after listening to the representation made by Professor Wan, could you please share your dataset?

> Hi, very pleased to study your work, could you please add your dataset to this repo, thank you.

**Comment by Logan-Lin** [comment]
Apologies for the (unbelievably) delayed response. To assist future researchers who come across this repository, I have recently reformatted the code and added an example dataset. If additional datasets are required, you can refer to those available in my other repository: https://github.com/Logan-Lin/TALE.
